import { chromium } from '@playwright/test';
const out = process.argv[2];
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const logs = [];
page.on('pageerror', (e) => logs.push(String(e)));
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
const field = page.locator('section[aria-labelledby="gap-title"] canvas').first();
const top = await field.evaluate((el) => el.getBoundingClientRect().top + window.scrollY);
await page.evaluate((y) => window.scrollTo(0, y - 900 * 0.7), top);
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/gap-searching.png` });
await page.evaluate((y) => window.scrollTo(0, y - 200), top);
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/gap-found.png` });
await browser.close();
console.log(logs.length ? logs.join('\n') : 'no page errors');
