import { chromium } from '@playwright/test';
const out = process.argv[2];
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const logs = [];
page.on('pageerror', (e) => logs.push(String(e)));
page.on('console', (m) => { if (m.type() === 'error') logs.push(m.text()); });
await page.goto('http://localhost:4173/report/krka', { waitUntil: 'networkidle' });
await page.waitForTimeout(4000);
await page.screenshot({ path: `${out}/report-top.png` });
const cover = page.locator('article[data-inspect]').first();
await cover.scrollIntoViewIfNeeded();
await page.waitForTimeout(1500);
const box = await cover.boundingBox();
if (box) { await page.mouse.move(box.x + box.width * 0.7, box.y + box.height * 0.7, { steps: 8 }); await page.waitForTimeout(900); }
await page.screenshot({ path: `${out}/report-cover.png` });
await page.goto('http://localhost:4173/initiate', { waitUntil: 'networkidle' });
await page.getByRole('textbox', { name: 'Company', exact: true }).fill('Elan d.o.o.');
await page.waitForTimeout(3000);
await page.screenshot({ path: `${out}/initiate.png` });
await browser.close();
console.log(logs.length ? logs.join('\n') : 'no console errors');
